### ISSUE TITLE
VMDK result is not recognized properly

### ISSUE THREAD

**Issue by hanselsen** [cisagov/ESXiArgs-Recover#10]
# 🐛 Summary #

I have followed the steps in the README, and also the referenced tutorial. Once I register the VMX, I see this:
![image](https://user-images.githubusercontent.com/1150323/218787678-71e174e1-4fdc-4394-8b23-9c0220084b2a.png)

Two things wrong with this: 
1. It says my hard disk is Thin Provisioned (which it is not).
2. It says that the disk size should be larger that its original capacity.

## To reproduce ##

1. Follow the README 
2. got the screenshot while registering

## Expected behavior ##

I would expect the disk to have the proper size.

**Comment by cablej** [comment]
Hi, can you share the output of “ls -la” in the VM directory and the contents of the vmdk file?

**Comment by hanselsen** [comment]
Sorry for not letting you know sooner. I concluded that I have been the victim of the second wave of attack. https://www.bleepingcomputer.com/news/security/new-esxiargs-ransomware-version-prevents-vmware-esxi-recovery/
We did not even try to recover from this, so we rebuilt all the VMs.
