### ISSUE TITLE
222

### ISSUE THREAD

**Issue by lhwbaby001** [cisagov/ESXiArgs-Recover#7]
# 🐛 Summary #

What's wrong? Please be specific.

## To reproduce ##

1. Do this
1. Then this

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by cablej** [comment]
Please let me know if you intended to file an issue / have specific questions.
